/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AttrPanel: typeof import('./src/components/editor/AttrPanel.vue')['default']
    Canvas: typeof import('./src/components/editor/Canvas.vue')['default']
    CodePreviewDialog: typeof import('./src/components/editor/CodePreviewDialog.vue')['default']
    ComponentRenderer: typeof import('./src/components/core/ComponentRenderer.vue')['default']
    Editor: typeof import('./src/components/editor/Editor.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    MaterialPanel: typeof import('./src/components/editor/MaterialPanel.vue')['default']
    PropsPanel: typeof import('./src/components/editor/PropsPanel.vue')['default']
    Renderer: typeof import('./src/components/core/Renderer.vue')['default']
  }
}
